### ISSUE TITLE
Annotate with /*#__PURE__*/ magic comment

### ISSUE THREAD

**Issue by adi518** [eight04/rollup-plugin-iife#10]
This is a cool plugin that can potentially solve a big problem. How can we annotate the IIFE with `/*#__PURE__*/`?

**Comment by eight04** [comment]
I don't know what does magic comment do but I guess you have to use the [banner](https://rollupjs.org/guide/en/#outputbanneroutputfooter) option.

**Comment by adi518** [comment]
It marks a piece of code as pure, making it tree-shakable.

**Comment by eight04** [comment]
This plugin wraps **output bundle** to iife. Why do you want to tree-shake the output?

**Comment by adi518** [comment]
It doesn't do it per export? I imagined it takes every export and wraps it into an IIFE, which I can then mark as pure, that's because without it, some parts of the module aren't detected as pure, such as `styleInject` calls, which appear in the global scope of the module.

**Comment by eight04** [comment]
> It doesn't do it per export?

No. This plugin modifies output result. Here is an example taken from the test file:

https://github.com/eight04/rollup-plugin-iife/blob/9296d9edaef1ff80a035797ac8f9dcc1d35d60a7/test/test.js#L49-L67

Also take a look at [es-iife](https://github.com/eight04/es-iife).

> it takes every export and wraps it into an IIFE, which I can then mark as pure,

I think the best solution is to use [rollup-plugin-shim](https://www.npmjs.com/package/rollup-plugin-shim). There is an example in README that shim `debug` module with an empty function so all `debug` function calls will be tree-shaken.

**Comment by adi518** [comment]
Whoa, I'll go check that out ASAP. Thanks. :)
