### ISSUE TITLE
Add `prefix` option

### ISSUE THREAD

**Issue by enkot** [eight04/rollup-plugin-iife#3]
It would be very useful to add `prefix` option.

### What is expected?

```js
//...
iife({
    prefix: '_my_'
})
```
Output file:
```js
var _my_componentA = (function () { //...
```

**Comment by eight04** [comment]
It seems reasonable to prefix those names which are generated automatically to avoid conflict. However, I'm not sure if we should also prefix names defined in `names` option.

**Comment by enkot** [comment]
Yes, agree with you. Can you check pull request #4?
